# The Docker image that will be used to build your app
image: node:lte
# Functions that should be executed before the build script is run
before_script:
  - npm i -g pnpm
pages:
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
