# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm install -g pnpm
pages:
  script:
    - export BASE_PATH=/$CI_PROJECT_NAME
    - pnpm i
    - echo VITE_API_URL=$VITE_API_URL >> .env
    - echo VITE_API_SALT=$VITE_API_SALT >> .env
    - echo VITE_VERSION=$CI_COMMIT_TAG >> .env
    - echo $VITE_API_URL
    - pnpm build
    - cp -a dist/. public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_TAG =~ /^v.*$/
